###

POST http://localhost:4000/users/reset-password/confirm
Content-Type: application/json

{
    "token": "token",
    "new_password": "lødingen"
}

###

###

POST rust-auth-production.up.railway.app/users/reset-password
Content-Type: application/json

{
  "email": "isakbjugn@gmail.com"
}

###