###

POST http://localhost:4000/users/reset-password/confirm
Content-Type: application/json

{
    "token": "v4.local.Ab0hVT3Zkrb-WVtVQQmN2Lq_1PEZi_c_yddkKmYRoafrkX_APqTWtAP0I0mZo0AnG8VDVMtXSK3pteX7X274ffuqFCMFqsY76BaAxYDYEqWTZZtJv8u9wZpkEFNAaf3H4wQ5O4y3x3s-B_-Cgk27oxwGMBKAKH4z7FfwuI6N4bIR1bDwTVMSnZlqX4uf2oOtHPC2SBFgDPB05vVwpC2QmSwEB1qRlwSZGtJ9w-CjAlBn0WDGtrxZMkxmarVSxdsHWdHeRARBsB45RsKMCWdN4rkBYMfnkM0o6b7p0pj-LG1h_l9h29go8DXDQ5G4SeZeYCSPQXH5MZUqisxMriNodTruR90_Rqk", 
    "new_password": "svolvær"
}

###

###

POST rust-auth-production.up.railway.app/users/reset-password
Content-Type: application/json

{
  "email": "isakbjugn@gmail.com"
}

###