###

POST http://localhost:4000/login/local
Content-Type: application/json
Accept: application/json

{
    "email": "isakbjugn@gmail.com",
    "password": "lødingen"
}

###

###

POST https://rust-auth-production.up.railway.app/login/local
Content-Type: application/json

{
  "email": "isakbjugn@gmail.com",
  "password": "lødingen"
}

###